env:
  browser: true
  es6: true
  node: true
  # jquery: true
extends: 
  - "eslint:recommended"
  - "kentcdodds/possible-errors"
  # - "kentcdodds/es6/possible-errors"
parserOptions:
  sourceType: module
rules:
  eqeqeq:
    - error
    - always
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
